# Generated by Django 5.1.5 on 2025-02-27 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposalrecord',
            name='bin',
        ),
        migrations.RemoveField(
            model_name='disposalrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='badges',
        ),
        migrations.CreateModel(
            name='WasteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('bin_type', models.CharField(choices=[('R', 'Recycling Bin'), ('C', 'Compost Bin'), ('L', 'Landfill Bin')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Bin',
        ),
        migrations.DeleteModel(
            name='DisposalRecord',
        ),
    ]
