# Generated by Django 5.1.5 on 2025-02-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disposal', '0002_remove_disposalrecord_bin_remove_disposalrecord_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasteitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='WasteItem',
        ),
    ]
